spring: 
    profiles: 
        active:
           - dev
---
server: 
    port: 8001
spring:
    profiles: dev
    application:
        name: spring-cloud-provider-dev
eureka:
    client: 
        service-url: 
            defaultZone: http://eureka01:7001/eureka/
---
server: 
    port: 8101
spring:
    profiles: test
    application:
        name: spring-cloud-provider-test
eureka:
    client: 
        service-url: 
            defaultZone: http://eureka01:7001/eureka/